### PR TITLE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

### PR DESCRIPTION
**Pull request by rgbkrk**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Legit 100% Python @jdfreder.

**Comment by jdfreder** [comment]
I like semicolons, but not in my python.  Be gone @rgbkrk !

**Comment by rgbkrk** [comment]
For those who stumbled here, we were chatting over Hangouts about semi-colons and their existence in JavaScript.

**Comment by jdfreder** [comment]
> For those who stumbled here, we were chatting over Hangouts about semi-colons and their existence in JavaScript.

lies

**Comment by rgbkrk** [comment]
You're right Jon, live free without semicolons.

**Pull request closed without merging**
