### PR TITLE
Check if the user is sudo, set User flag default accordingly.

### LINKED ISSUE #7: Detect when user=True should be passed to install_nbextension
With non-root installations (where the user asks to do local install, etc.), `user` needs to be set to `True` in the call to `install_nbextension`.

Suggested by @carreau in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/YfeORebzBnk/ps4ql2Kvv9EJ

### PR DESCRIPTION
**Pull request by jdfreder**
@rgbkrk

closes #7

### CODE REVIEW

**Comment by jdfreder** [comment]
@rgbkrk this actually does a user id check to see if the user is root.  This seems to work well in my tests...

**Comment by rgbkrk** [comment]
How does that work in Windows?

**Comment by rgbkrk** [comment]
Thanks for hopping on my issues by the way. :smile:

**Comment by jdfreder** [comment]
Actually, I haven't tested it on Windows yet.  If it doesn't work, I could just do an OS check before trying to set the flag and then use a Win32 API call to see if the account is an administrative account.

**Comment by rgbkrk** [comment]
Would falling back to user=True make sense? How do we normally do it? Sometimes we end up in the `.ipython` folder regardless.

**Comment by jdfreder** [comment]
Yeah, falling back to user=True would work for an administrative account too.  That's probably the best bet for Windows.

**Comment by jdfreder** [comment]
#11 to remind myself to do that.

**Pull request merged**
