### PR TITLE
:wheelchair: provide user friendly error messages

### PR DESCRIPTION
**Pull request by chfw**
A more user friendly message could help user realize that they have not gotten any installed yet. So they should be able skip them or retry.

https://github.com/chenjiandongx/pyecharts/issues/105, https://github.com/chenjiandongx/pyecharts/issues/102

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm not sure of the state of this repo, happy to see fixes come in though.

**Comment by chfw** [comment]
The updated behavior is:

1) if jupyter is installed, nbextensions will be installed
2) otherwise, no installation and no exception, hence the whole setup won't abort. 
3) User need to specify '-v' upon installation to see the added user friendly message, due to this reason here:  https://github.com/pypa/pip/issues/2933

**Comment by jdfreder** [comment]
SGTM - I can publish this later. I don't have auth to from here.

**Comment by chfw** [comment]
Thanks for the update and quick response. A lot of open source users of pyecharts are facing the same issue but we have provided a workaround. I look forward to your next release.

**Comment by jdfreder** [comment]
✔️ This is published as 0.3.1

**Comment by chfw** [comment]
I think pyecharts users will be made very happy by your release too.

**Pull request merged**
