### PR TITLE
Added win32 check for IsUserAnAdmin()

### PR DESCRIPTION
**Pull request by costerwi**
Based on accepted answer to "[Cross-platform way to check admin rights in a Python script under Windows?](http://stackoverflow.com/questions/1026431/cross-platform-way-to-check-admin-rights-in-a-python-script-under-windows)".

### CODE REVIEW

**Comment by rgbkrk** [comment]
Seems alright.

**Comment by jdfreder** [comment]
Thanks!

**Comment by jdfreder** [comment]
Whoops, forgot to push this to PYPI.  I'll do that now.

**Comment by jdfreder** [comment]
Ok uploaded! (0.3)

**Comment by rgbkrk** [comment]
:cake:

**Pull request merged**
